### ISSUE TITLE
2 plugin listing on the plugin page

### ISSUE THREAD

**Issue by dhanendrannewscorp** [sailthru/sailthru-wordpress-plugin#48]
We can able to see 2 plugin listing on the plugins page.
<img width="1075" alt="screen shot 2017-11-09 at 6 30 46 pm" src="https://user-images.githubusercontent.com/19810308/32606672-318344b8-c57c-11e7-914c-25f214b4b298.png">

This is because of having 2 files in the same directory.
1. [sailthru.php](https://github.com/sailthru/sailthru-wordpress-plugin/blob/master/sailthru.php)
2. [plugin.php](https://github.com/sailthru/sailthru-wordpress-plugin/blob/master/plugin.php)

Can we remove `sailthru.php` or move all code from `plugin.php` to `sailthru.php` and remove it?

**Comment by nickgundry** [comment]
@dhanendrannewscorp It's actually because both those files have the WordPress headers. There's a commit that should resolve that here. 

https://github.com/sailthru/sailthru-wordpress-plugin/commit/d7db1172b049048b1efbd18c0e477db370013da1
